### ISSUE TITLE
Create rules for terminal in order to be listed as supported

### ISSUE THREAD

**Issue by zrzka** [crossterm-rs/crossterm#197]
There's this Tested Terminals section in most of the READMEs. What does this exactly mean? Let's say I'd like to add Terminal.app, iTerm2.app, etc. on macOS. I do not expect any issues, but you never know.

What's the procedure here? Was trying to find a test tool, list of manual steps, etc. but can't find anything.

**Comment by TimonPost** [comment]
Right good question, so those terminals are the ones I have tested manually and validated that they worked. There is no procedure here actualy. Although that is a good idea since people might want to add terminals to that list.

**Comment by zrzka** [comment]
What about an interactive test tool? Still not convinced it's the right way, but at least something to start with. Will share my idea in a separate branch in a couple of days.

**Comment by TimonPost** [comment]
That would be great, testing a terminal is a bit difficult, like when I want to test a terminal resize, the terminal will resize in the unit tests, it is a bit weird if unit tests affect the state of the terminal and can cause unpredictable results as well. So there are possible ways to do that correctly without executing system calls,  and would love to see proposals. The easy way would be to just make a checkmark list with items a terminal should adhere to in order to get onto that tested terminal list

**Comment by zrzka** [comment]
@TimonPost check the [zrzka/visual-interactive-test](https://github.com/zrzka/crossterm/commits/zrzka/visual-interactive-test) branch in my fork. It's something in-between list of items to check manually & auto tests without executing system calls. Just a rough idea. It's not meant as unit / integration tests replacement, it's just something for the users - a) here're more examples for you, b) run it, go through all steps, attach report to the issue and then the list of tested terminals can be enhanced.

**Comment by TimonPost** [comment]
@zrzka Amazing work!! This is just great, I will have a look at it as soon as I can.

**Comment by TimonPost** [comment]
Going to close this issue, will mention the interactive example somewere in the readme
