### ISSUE TITLE
Implement Colorize for Strings

### ISSUE THREAD

**Issue by Avarel** [crossterm-rs/crossterm#318]
I noticed that `Colorize` was only implemented for `&'static str` and not `String`. This feels incredibly restrictive for a case like this:

```rust
fn what() -> String {
    format!("{}", 123).on_green().to_string()
}
```

This causes error with the borrow checker such as:
```rust
   |
   |     format!("{}", 123).on_green().to_string()
   |     ^^^^^^^^^^^^^^^^^^-----------
   |     |
   |     creates a temporary which is freed while still in use
   |     argument requires that borrow lasts for `'static`
   | }
   | - temporary value is freed at the end of this statement
   |
```

Is there an alternative way to do what I would like to do within this crate?

**Comment by TimonPost** [comment]
Calling `to_string` on `on_green` is not possible. Because `on_green` will return `StyledContent` type.
What kind of `String` result do you want to return in that function? With crossterm the style is not stored in the string but in the `StyledContent` which contains the string and style.

maybe this (not sure)
```
let style = format!("{}", 123).as_str().on_green()
```

or 
```
let style = crossterm::style::style(format!("{}", 123)).on_green();
```

**Comment by Avarel** [comment]
The second example worked well for my use case, thank you!
