### ISSUE TITLE
Rename and move Output command

### ISSUE THREAD

**Issue by zrzka** [crossterm-rs/crossterm#320]
I feel that the `utils` module isn't a very good home for the `Output` command.

What do you think about ...

* moving it to the `style` module,
* renaming it to `Print` (or `PrintContent`) to sync it with the `PrintStyledContent`

?

**Comment by TimonPost** [comment]
I have some idea for this, we might get rid of this command.  I will elaborate more on this later.

**Comment by TimonPost** [comment]
I had some toughts about this. 

It would be nice if we could somehow pass displayable types like string, int directly into the `execute`, `queue` macro's. This is similar to what you have in anes. However, this is a bit tricky since we expect windows systems that there is an `execute_winapi` which comes from the `Command` trait and a string does not implement this. 

Let's rename it to `Print` since it mimics `print!` and fits the `PrintStyledContent`, good idea to move it into the styling module.

**Comment by TimonPost** [comment]
#326

**Comment by dantho** [comment]
Top level Readme includes getting Started section that no longer compiles due to a missed Output -> Print translation:
From the Readme:
`use crossterm::{execute, ExecutableCommand, style::{Attribute, Color, SetForegroundColor, SetBackgroundColor, ResetColor}, Output, Result};`
This works:
`use crossterm::{execute, ExecutableCommand, style::{Attribute, Color, SetForegroundColor, SetBackgroundColor, ResetColor, Print}, Result};`

**Comment by TimonPost** [comment]
Thanks. Going to update directly.

**Comment by TimonPost** [comment]
Closing, fixed in 0.14
