### ISSUE TITLE
Add a function to set terminal emulator's title

### ISSUE THREAD

**Issue by Jarqwiz** [crossterm-rs/crossterm#347]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a function to set the terminal emulator's title in a cross-platform fashion.

**Describe the solution you'd like**
It could be something like `crossterm::terminal::set_title(title: &str)`.
This function would change the window's title from something like `cargo run` or `./my_app` to something like `MyApp` indicated by the `title` parameter.

**Additional context**
I haven't found any crate that would implement this kind of behavior.
I have found something like this from [hunter](https://github.com/rabite0/hunter/blob/17c25221241c61acf6a77967471439775829abe8/src/term.rs#L57), but it seems to work only on Linux.

**Comment by TimonPost** [comment]
Good idea! I would like to support this within crossterm.

**Comment by Jarqwiz** [comment]
I'm pretty sure that the ANSI sequence is the best approach on Unix-like platforms. On Windows, [`SetConsoleTitle`](https://docs.rs/winapi/0.3.8/winapi/um/wincon/fn.SetConsoleTitleW.html) could be used.

**Comment by matheuslessarodrigues** [comment]
Do you know if there's a way to restore title when the application ends?
I see that, on windows, we can store the original title with `GetConsoleTitleW`, and then set it later.
However, I don't know how to achieve that with ANSI sequences.

Asking, because I'm willing to make a PR. I'd like this feature in my application :)

**Comment by Jarqwiz** [comment]
Hello there! It's nice to see someone willing to make this PR.

So with a quick search, I couldn't find any way to get the title only set the title. On the other hand, I don't think it is a problem, because AFAIK shell will automatically set the title to whatever the user has defined for it (often the current working directory). So the application does not have to care about resetting the title, because it's automatically reset when the application exits. You might find something useful from here https://www.tldp.org/HOWTO/pdf/Xterm-Title.pdf.

**Comment by matheuslessarodrigues** [comment]
You're right! It does seem that the window's title is reset automatically (tested on powershell, cmd and git's bash all on windows). I guess I didn't notice it because I mainly use busybox's shell and it does not do that.

Anyways, we can focus on just implementing the `terminal::set_title(title: &str)` function?
If I'm not wrong, I should also make a PR to `crossterm-winapi` adding the `SetConsoleTitleW` there, right?

I may add that, at least on latest Windows 10, using `"\x1b]0;my window title\x07"` works.

**Comment by TimonPost** [comment]
Nice!

> I should also make a PR to crossterm-winapi?
It is not a requirement but would be great when submitted, I will merge it and release a version. 

> terminal::set_title(title: &str)
Everything that can work with ANSI codes should go via the commands API. There are a lot of commands already implemented which you can take as reference. The reason for this is that the ANSI codes will be executed on the user passed buffer.

**Comment by matheuslessarodrigues** [comment]
Oh, right! So then we can make a new command `crossterm::terminal::SetTitle`.

The question is: since it seemingly works with ANSI codes in windows, should we just stick with the ANSI codes for everything or should we first add the `SetConsoleTitleW` to `crossterm-winapi` and then use that to implement `SetTitle` on `crossterm`?

**Comment by TimonPost** [comment]
If I look at the Microsoft documentation `SetConsoleTitleW` does not require a HANDLE in order for it to work. We could move the function into [Console](https://github.com/crossterm-rs/crossterm-winapi/blob/master/src/console.rs) struct, however, that type is mainly meant for operations that do require a `HANDLE`. So I think it is better to not move this function into the winapi crate. And just keep it in the `terminal::sys::windows` [module](https://github.com/crossterm-rs/crossterm/blob/master/src/terminal/sys/windows.rs). After that, an re-export in [sys.rs](https://github.com/crossterm-rs/crossterm/blob/master/src/terminal/sys.rs) should be made.

For the windows code `SetTitle` will call: `sys::set_title` and for the ANSI code you'll have to return the ANSI code. The ANSI code can be added [here](https://github.com/crossterm-rs/crossterm/blob/master/src/terminal/ansi.rs) with the rest. 

A note on windows. You mentioned that the ANSI code worked for windows as well right? If this is not the case your `SetTitle` command should override this function and return false. Otherwise, crossterm will try to execute the command on windows while the ANSI code is not supported for the platform. 

```
    #[cfg(windows)]
    fn is_ansi_code_supported(&self) -> bool {
        super::ansi_support::supports_ansi()
    }
``

You don't have to care about making the ANSI code execute on windows 10, crossterm will [do](https://github.com/crossterm-rs/crossterm/blob/master/src/macros.rs#L33) this for you.

**Comment by matheuslessarodrigues** [comment]
Just made a PR #429

**Comment by Jarqwiz** [comment]
Closing the issue as PR (#429) got merged.
