### ISSUE TITLE
AZERTY keyboard suppoirt (Windows)

### ISSUE THREAD

**Issue by 3kyro** [crossterm-rs/crossterm#359]
**Describe the bug**
In AZERTY keyboards (Belgian french in this case) some common ascii characters ( { ,} , [, ] , #, \ ) are only accessible with the right Alt button pressed. In windows, no event is generated for these characters.

**To Reproduce**
1. Run the event-poll-read example on a windows/AZERTY machine and try to get a KeyEvent for any of the above characters

**OS**
 - Windows 10

**Terminal/Shell**
 - CMD/Powershell

In crossterm/src/event/sys/windows/parse.rs there is no differentiation of right or left key pressed

`let alt = state.has_state(LEFT_ALT_PRESSED | RIGHT_ALT_PRESSED);`

while later in the same file, in `parse_key_event_record` function the key code is replaced by the virtual_key_code which no longer corresponds to the right character.

``` Rust
                if modifiers.contains(KeyModifiers::ALT) {
                    // If the ALT key is held down, pressing the A key produces ALT+A, which the system does not treat as a character at all, but rather as a system command.
                    // The pressed command is stored in `virtual_key_code`.
                    let command = key_event.virtual_key_code as u8 as char;

                    if command.is_alphabetic() {
                        character = command;
                    } else {
                        return None;
                    }
```

Here is also an output from the event-poll-read example with some debug information.

```
[src\event\sys\windows\parse.rs:80] character_raw = 93
[src\event\sys\windows\parse.rs:88] command = 'º'
Event::Key(KeyEvent { code: Char('º'), modifiers: CONTROL | ALT })
```

**Comment by TimonPost** [comment]
Thanks for filing the issue, your correct, crossterm in general does not differentiate between left/right ctrl, shift, control. I will have to look into those key codes.

**Comment by sharnoff** [comment]
This seems to be somewhat related to #373 - given the limitations of other terminal applications (and the documentation for xterm, etc.) it seems like terminal emulators won't actually provide different key codes for left/right control or shift+ctrl. More info: [https://vi.stackexchange.com/a/4291](https://vi.stackexchange.com/a/4291).

**Comment by sigmaSd** [comment]
Hi, removing the else clause here fixes the issue
```rust
                if modifiers.contains(KeyModifiers::ALT) {
                    // If the ALT key is held down, pressing the A key produces ALT+A, which the system does not treat as a character at all, but rather as a system command.
                    // The pressed command is stored in `virtual_key_code`.
                    let command = key_event.virtual_key_code as u8 as char;

                    if command.is_alphabetic() {
                        character = command;
                    } else {
                        return None;
                    }
```
example of output: `Event::Key(KeyEvent { code: Char('{'), modifiers: CONTROL | ALT })`
Can we just do that or are there some drawbacks that I didn't consider?

**Comment by TimonPost** [comment]
Actualy, I am not sure anymore why this alphabetic check is there. Maybe this check should not restrict to A-Z but also include characters like: `{`.

**Comment by sigmaSd** [comment]
My opinion is to leave the check since its not obvious what it is for and remove the else clause.
On my testing some keys generate  `\u{0}` like `alt +1` which is supposed to generate no event (there is no alt key counterpart) or at least generate the same key `&`
I did more testing and there are different keys that output `\u{0}` or to be more accurate `character_raw =0`, for example `alt + 1`, `numpad_lock`, and keys that needs two click to work like `^` or `¨` (they generate two events the first one gives 0 the second gives ^ or ¨), so I think adding a check like `if character_raw == 0 {return}` is a good idea to ignore all those events

**Comment by sigmaSd** [comment]
Regarding the keys that need two events, its looks like they are a bit more troublesome.
We have two cases taking `^` as an example:
1) first click generate `0` 2nd click generates `^^` (2 instead of the expected one)
2) first click generate `0`, for the 2nd click if now I click on  a letter instead (for example letter `a`) it generates `â` (the correct output)

So two problems, 
- the generating 0 as said in the previous comment can be ignored with an early return
- the second problem is the duplicate output in the first case shown here. I don't see here an obvious solution for this one
