### ISSUE TITLE
Make ContentStyle lighter with a bitmask

### ISSUE THREAD

**Issue by Canop** [crossterm-rs/crossterm#376]
The ContentStyle is cloned when you apply it. Depending on the application, there might be a lot of those clonings, and of content_styles in memory.

The struct currently contains a vector of attributes. Attribute is an enum with 24 values. Using a bitmask instead of a vector would result in a lighter structure and in faster add/remove/read operations.

The API would be changed a little (as the vector is public) but the change is probably easy to manage.

If nobody objects, I can look into proposing a PR for this.

**Comment by Canop** [comment]
Replacing the `Attribute` enum with an `Attributes` bit set seems to make a lot of sense but the work is a tad intimidating after a first review:

- exposing `Attributes` and the constants in a `crossterm::style::attributes` module
- replacing the `SetAttribute` command with a `SetAttribute`s one, which functionally isn't exactly the same as it can be used to change several attributes at once (maybe "keep" the old one as an alias to `SetAttributes`)
- implementing writing the csi/sgr sequence from the Attributes
- implementing the Windows writing
- rewrite all existing style tests
- fix the documentation

I can't make a PR for all this alone. A shared idea of the goal is needed and somebody would have to do the Windows part and I'd like to have some help for the unit tests too.

**Comment by TimonPost** [comment]
I remembered pancurses to have a similar implementation.  See [here](https://github.com/ihalila/pancurses/blob/master/src/attributes.rs).

They have an `Attribute**s**` struct which wraps a raw value (byte) and uses trait implementations for mapping the enum `Attribute` to a numeric value. This way we can also still keep the `Attribute` enum. Which would cause no breaking changes? As you said we can create a new command `SetAttributes` change `ContentStyle` to have the new `Attribute**s**` type and use bit or to add attributes to that type. Please check the link in order to get a better understanding.

**Comment by Canop** [comment]
The pancurses implementation seems OK.
There are still breaking changes as the Vec<Attribute> is public but it can indeed be done in a less traumatic way and eases dynamic styling.

**Comment by TimonPost** [comment]
Completed
