### ISSUE TITLE
Question: Cursor interaction with variable-width characters

### ISSUE THREAD

**Issue by Aryailia** [crossterm-rs/crossterm#458]
I have a couple of questions. So I'm trying make an input bar where you can type and delete. The terminal emulator I am using is [st](http://st.suckless.org/)

If you were type "你好嗎":

- then backspace, you get "你好 " with an extra space in both raw and non-raw crossterm input as they are full-width
- It takes two cursor::MoveLeft(1) to move through a single character. Thus moving left twice then print space is yields the expected behavior for backspace.

Additionally, I might want to consider how to handle emoji. Examples from [unicode-width](https://github.com/unicode-rs/unicode-width):

```rust
assert_eq!(UnicodeWidthStr::width("👩"), 2); // "\u{1f469}", woman
assert_eq!(UnicodeWidthStr::width("🔬"), 2); // "\u{1f52c}", microscope
assert_eq!(UnicodeWidthStr::width("👩‍🔬"), 4); // "\u{1f469}\u{200d}\u{1f52c}", woman + zero-width join + microscope = female scientist
```

But in the user-perceived width (if implemented correctly) of the female scientist should be two. Crossterm on the st terminal displays 👩🔬 (two full-width characters). Incidentally, to delete this properly, I could choose to anything from requiring 1-3 backspaces. I imagine most terminal emulators do not implement unicode "correctly" so I can't rely on precomputing.

In particular, I would like to keep track of what is being typed and have that synced with what is being displayed on the terminal. So ideally a delete would work both on the displlay

# Possible Solutions/Questions
- Prioritise my own output buffer: delete a character, issue a `ClearType::CurrentLine` and reprint the line
- Is there a way to access the internal tty display buffer? Though I imagine this is not the desired solution
- Some form of after every `stdout.execute(Print())`, call `cursor::position()` to keep track of display size. How expensive is calling `cursor::position()`?
- Open an alternative screen, print, and use that for calculation. I assume you can only open one alternative screen. Is opening an alternative screen expensive?

Or is there a function provided in Crossterm or do you have an advice?

**Comment by TimonPost** [comment]
Might https://github.com/unicode-rs/unicode-width be an option here? It will return the with in cells of a character.

**Comment by Aryailia** [comment]
My emoji example is pulled from unicode-width. The problem is with using the unicode-width crate is on two-fold:

1. It calculates the wrong value.  [github/sbillig/rust-grapheme](https://github.com/sbillig/rust-grapheme) calculates the 'right' value, i.e. for the third emoji in my above example
  * `unicode-width("👩‍🔬") == 4`
  * `rust-grapheme("👩‍🔬") == 2` (what the program should display)
2. Even if I were to use rust-grapheme, the terminal emulator could either the two above, or render something else entirely, depending on its implementation (and indeed my current terminal does the 'wrong' thing and aligns with unicode-width)

Now maybe the answer is just to support terminals individually. But I'm making a text editor basically, so this is a central feature, so I would hope for something more robust. Like reprinting the current line on delete sounds robust to me and probably less call intensive than polling the cursor constantly... but is it?

**Comment by TimonPost** [comment]
> Now maybe the answer is just to support terminals individually

I am not very aware on how to build a solid text editor. I know of some rust editors that use rust and or crossterm. You might get better answers there since they probably have had to deal with this issue. The author of ReVim and broot are in the crossterm discord for if you might want to ask a question.

https://github.com/cowboy8625/ReVim
https://github.com/xi-editor/xi-editor/tree/master/rust
https://github.com/Canop/broot

What I can say is that when writing your own text editor its common to keep a leading buffer in memory. The idea with clearing and redrawing the lines seems good to me. 

> Is there a way to access the internal tty display buffer? Though I imagine this is not the desired solution

What do you want to do with it? You don't want to edit this buffer. 

Crossterm does't do any real magic. What it does in case of `Print` is calling a `write` to your given writer. You can pass your own writer to crossterm which will then execute the commands to that buffer. Its very low level in te sense that it will output what you give it. 

I found this crate as well. Could this be of any use:

https://github.com/unicode-rs/unicode-segmentation

**Comment by Aryailia** [comment]
Oh, I didn't realise there was a discord, I would have asked there instead. And thanks for the links.

> What do you want to do with it? You don't want to edit this buffer.

I was just going to use the buffer to read what was printed, but yeah I don't think it's a good idea. It was just one of the ideas I was reaching for.

**Comment by hronro** [comment]
Hello @Aryailia, have you found a solution? What is your final decision?
