### ISSUE TITLE
Cursor position regression with crossterm 0.17.6

### ISSUE THREAD

**Issue by sigmaSd** [crossterm-rs/crossterm#462]
**Describe the bug**
cursor::position() panics when changing the resolution of the terminal at the same time

**To Reproduce**
```rust
fn main() {
	loop {
		crossterm::cursor::position();
	}
}
```
Changing the terminal size while this code is running will make it panic with: 
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Other, error: "The cursor position could not be read within a normal duration" })', src/main.rs:3:18```

**OS**
 - Arch Linux

**Terminal/Console**
 - Gnome Terminal

**Other**
This panic does *not* happen with crossterm 0.17.5

**Comment by TimonPost** [comment]
I don't hope that this has to do with the mio 0.7.0 update. Thanks for reporting! Mio has switched to edge-level io triggering, the first crossterm was using level triggering. There might be some issues in this triggering behavior. 

#435

**Comment by TimonPost** [comment]
I will have to debug this issue my self to see what's going on here.

**Comment by sigmaSd** [comment]
I think I figured the issue. 
See: https://docs.rs/mio/0.7.0/mio/struct.Poll.html#notes also from the change-log `Poll::poll_interruptible was removed. Instead Poll::poll will now return an error if one occurs.`
So now this code-path is taken https://github.com/crossterm-rs/crossterm/blob/master/src/event/read.rs#L80
It used to be never taken in older versions because mio retried automatically if interrupted.
So now its crossterm responsibility to retry when it gets `io::ErrorKind::Interrupted`.

**Comment by TimonPost** [comment]
Ah! Thanks that makes sense. There is one issue because the interruptable event is also thrown by crossterm when a wake token occurs:

https://github.com/crossterm-rs/crossterm/blob/master/src/event/source/unix.rs#L142

Maybe will have to move [this](https://github.com/crossterm-rs/crossterm/blob/master/src/event/read.rs#L78) error to [here](https://github.com/crossterm-rs/crossterm/blob/master/src/event/source/unix.rs#L82):
