### ISSUE TITLE
Why are ANSI escape sequences used in Windows 10?

### ISSUE THREAD

**Issue by Koxiaet** [crossterm-rs/crossterm#499]
I don't know if the issue tracker is the right place to ask questions, but I wanted to know why Crossterm prefers ANSI escape sequences over WinAPI when Windows supports both. Surely just supporting WinAPI on Windows and ANSI on Unix would be a lot less code?

In particular I'm working on #495, and I find that implementing everything could be so much simpler if WinAPI was always used on Windows.

**Comment by TimonPost** [comment]
A good question.

- First reason is that most of the ANSI escape codes are universal today. Windows 10 Windows has switched  to that kind of processing because there were many requests for its support. People wanted to write ANSI codes cross-platform. 
- The second reason would be that things like coloring, resizing, clearing are way easier with ANSI codes than when doing it all manual via WinAPI. In the end, ANSI will be translated to WinApi calls by Windows anyways.  I prefer to rely on their Winapi behavior. It's probably well written and well tested. 
- ANSI escape codes allow for easy buffering since you can just write Ansi to the output without flushing. When using windows 7 for crossterm for example you won't have this feature. In order to replicate this behavior you would need to keep some state somewhere. And crossterm is trying to reduce any kind of state leaving everything up to the user.

**Comment by Koxiaet** [comment]
That last point is interesting, so I did some reading and I discovered that on newer Windows versions console API commands are actually translated into VT commands, from [this blog post](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/):

> When a legacy Command-Line app uses a Console API like WriteConsoleOutput(...), the specified text is written to the attached ConHost’s Output Buffer. Periodically, ConHost renders changed areas of the Output Buffer as text/VT which is sent via stdout back to the Console.

So it seems that using VT escape sequences is actually the least overhead way to go!

Now I'm wondering whether to create a fake Terminfo for Windows' terminal if Windows 10 is detected or to hardcode Windows-compatible escape sequences into every implementation of `Command`...
