### ISSUE TITLE
inconsistent reporting of ^Enter

### ISSUE THREAD

**Issue by pm100** [crossterm-rs/crossterm#508]
on version 0.18 with raw mode enabled

If I type Ctrl+Enter

 - on windows I get Key = enter, mods = ctrl
 - on linux I get key = j, Mods = ctrl

The linux one seems wrong

**Comment by pm100** [comment]
test app - using doc sample

```
use crossterm::event::{read, Event};

fn print_events() -> crossterm::Result<()> {
    loop {
        // `read()` blocks until an `Event` is available
        match read()? {
            Event::Key(event) => println!("{:?}", event),
            Event::Mouse(event) => println!("{:?}", event),
            Event::Resize(width, height) => println!("New size {}x{}", width, height),
        }
    }
    Ok(())
}

fn main(){
    crossterm::terminal::enable_raw_mode();
    print_events();
}
```

run this on linux and go ctrl+enter
![image](https://user-images.githubusercontent.com/489231/98323585-f7f11d80-1f9e-11eb-95dd-60cb3aff6082.png)

**Comment by imsnif** [comment]
Can confirm, same here.

**Comment by imsnif** [comment]
Found the issue. For me this happened because of this line: https://github.com/crossterm-rs/crossterm/blob/master/src/event/sys/unix/parse.rs#L76

I was in raw mode, but didn't use crossterm to enter raw mode (I was using `tcsetattr` from termios). Crossterm was checking its own internal state to see whether I was in raw mode and that's why this issue happened.

**Comment by TimonPost** [comment]
@pm100 I tried it on an xterm terminal and I seem to get the ENTER but not the CTRL. Perhaps you can trie what @imsnif proposed?

**Comment by pm100** [comment]
@TimonPost what is he suggesting? In my code I used what he suggests

**Comment by TimonPost** [comment]
Enabling raw modes? What terminal are you using on Linux?
