### ISSUE TITLE
Shift + F3 Key Event not read.

### ISSUE THREAD

**Issue by thinkingreed** [crossterm-rs/crossterm#513]
Shift + F3 Key Event not read.
Shift + F2 and Shift + F4 are read correctly.

■ Verification environment
・ Ubuntu 20.04
・ Ubuntu20.04 on WSL
・ Ubuntu 18.04

■ Program
Implemented as in the example below.
crossterm/examples/event-stream-tokio.rs

Sorry to trouble you, but please confirm.

**Comment by TimonPost** [comment]
I validated it, it seems true that `SHIFT + F3` is not correctly handled. The other F keys seem to behave perfectly.

**Comment by thinkingreed** [comment]
I understand. Thank you for watching.
I will also analyze the weekend.

**Comment by MitMaro** [comment]
Did some digging into this tonight:

The issue seems to stem from the match here: https://github.com/crossterm-rs/crossterm/blob/f7063d9160671ab3be4b4add8d19271abb022cbd/src/event/sys/unix/parse.rs#L162

On my system at least, Shift + F3 produces a buffer of `[27, 91, 49, 59, 50, 82]`, which incorrectly matches the `b'R'` arm of the match.

This matches the CSI for the cursor position, I'm not sure how this can be handled.

**Comment by TimonPost** [comment]
Closing in favor of https://github.com/crossterm-rs/crossterm/issues/685.
