### ISSUE TITLE
Question: Rendering content in raw mode that exceeds current terminal viewport

### ISSUE THREAD

**Issue by SirWindfield** [crossterm-rs/crossterm#550]
I print a list of items inside of raw mode. If the user's prompt is at the bottom of the terminal viewport while I enter raw mode, the list does only get partially displayed. Lines that would exceed the current viewport are not rendered (the terminal doesn't automatically "scroll" down to show them).

I am currently working around it by printing the number of required lines in normal mode and move up again before I enter raw mode. It works, but feels more like a hack. 

Is there a better workaround for this? I just wonder on how to deal with this in the cleanest way possible.

```rust
let number_of_items = self.values.len();

// XXX: Newlines are not processed inside of raw mode. Print the needed number
// of lines on the console during normal mode to take advantage of "scrolling",
// as the list items might be out of the current user's viewport otherwise.
for _ in 1..number_of_items {
    queue!(stdout, Print("\n")).unwrap();
}
// Move back to the previous position.
queue!(stdout, MoveToPreviousLine(number_of_items as u16)).unwrap();

// Here I enter raw mode and print the list of items.
for item in items {
	queue!(stdout, Print(item), MoveToNextLine(1)).unwrap();
}
```

**Comment by TimonPost** [comment]
Late response. But I am not aware of any good workaround. Perhaps you can ask around in the discord server where there are people who have build editors with crossterm.  They know more about the practical implementation details. Let me close this issue because it is not really about crossterm but rather a usage related (unless you disagree feel free to open)
