### ISSUE TITLE
Help managing ScrollUp

### ISSUE THREAD

**Issue by elferherrera** [crossterm-rs/crossterm#623]
Hi,

Wasn't sure if this was a bug or feature. We are working on [reedline](https://github.com/nushell/reedline) which uses crossterm to do all its magic. Now Im working on trying to implement a way to process buffers that are larger than the available screen size. One thing that we have noticed is that on `ScrollUp` all the text that was above the visible area in the terminal gets `eaten`. 

Have a look at this
![Animation](https://user-images.githubusercontent.com/6942205/147857564-024125e8-5f08-466f-8ca0-237029da630d.gif)
See how the line with the `start--` marker disappears after the scroll up event

Is there a way you can recommend for dealing with this case? 
how can the rows above the visible area be protected?

Thanks in advance

**Comment by TimonPost** [comment]
So crossterm just executes the `ESC [ <n> S` command and leaves the implementation over to the terminal driver. In your case, Microsoft is responsible for scrolling the contents of the screen inside the scrolling margin. They state the [following](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#scrolling-margins):

![image](https://user-images.githubusercontent.com/19969910/147858690-3980d229-365a-4f0f-9104-199e3fc9fcf8.png)

_Also important to note is scroll up and down are also affected by the scrolling margins. Scroll up and down won’t affect any lines outside the scrolling margins. (scrolling margins being the whole visible buffer I assume)_

Maybe that this last note could be the issue of your problem? As you scroll up, the contents above the visual buffer will remain to be in the same position, but the rest will be moved up and therefore overwriting lines. The only reasonable thing I can think of, but im not a TUI developer, is storing the terminal buffer in your application since you want fine control about what's being displayed and what isn't displayed.

**Comment by elferherrera** [comment]
Thanks for the note. I appreciated.

I think I understand what the problem is. Now I need to figure how to store the buffer
