### ISSUE TITLE
Not able to stop control+M from being an Enter

### ISSUE THREAD

**Issue by wags-1314** [crossterm-rs/crossterm#633]
I am using crossterm to make a text editor of sorts. I am switching into raw mode and simply echoing the keypresses. Here is my code:
```rust
use std::time::Duration;

use crossterm::{
    event::{poll, read, KeyCode::Char, KeyEvent, KeyModifiers},
    terminal, Result,
};

fn print_events() -> Result<bool> {
    loop {
        if poll(Duration::from_millis(100))? {
            let ev = read()?;
            print!("{:?}\r\n", &ev);
            match ev {
                crossterm::event::Event::Key(KeyEvent {
                    code: Char(ch @ 'q'),
                    modifiers: KeyModifiers::CONTROL,
                }) => { print!("cntrl{{{}}}\r\n", ch); break; },
                crossterm::event::Event::Key(KeyEvent {
                    code: Char(ch),
                    modifiers: KeyModifiers::CONTROL,
                }) => print!("cntrl{{{}}}\r\n", ch),
                crossterm::event::Event::Key(KeyEvent {
                    code: Char(ch),
                    modifiers: KeyModifiers::ALT,
                }) => print!("{}\r\n", ch),
                crossterm::event::Event::Key(KeyEvent {
                    code: Char(ch),
                    modifiers: _,
                }) => print!("{} ({})\r\n", ch, ch as u8),
                _ => break,
            };

            print!("\r\n");
        }
    }

    Ok(true)
}

fn main() -> Result<()> {
    terminal::enable_raw_mode()?;
    print_events()?;
    terminal::disable_raw_mode()?;
    Ok(())
}
```

When I enter `control+M` I get `Key(KeyEvent { code: Enter, modifiers: NONE })` instead of `Key(KeyEvent { code: Char('m'), modifiers: CONTROL })`. How do I make this happen?

**Comment by TimonPost** [comment]
Platform and terminal?

**Comment by markus-bauer** [comment]
I noticed this also. I'm using Ubuntu 21.10. It's not terminal dependent (same results in xterm, kitty, gnome-terminal, urxvt). Here are some results (I would like someone else to also test this):

```
Ctrl+m: KeyEvent { code: Enter,     modifiers: NONE }
Ctrl+c: KeyEvent { code: Char('c'), modifiers: CONTROL }
Ctrl+j: KeyEvent { code: Char('j'), modifiers: CONTROL }

Ctrl+1: KeyEvent { code: Char('1'), modifiers: NONE }
Ctrl+2: KeyEvent { code: Char(' '), modifiers: CONTROL }
Ctrl+3: KeyEvent { code: Esc,       modifiers: NONE }
Ctrl+4: KeyEvent { code: Char('4'), modifiers: CONTROL }
Ctrl+5: KeyEvent { code: Char('5'), modifiers: CONTROL }
Ctrl+6: KeyEvent { code: Char('6'), modifiers: CONTROL }
Ctrl+7: KeyEvent { code: Char('7'), modifiers: CONTROL }
Ctrl+8: KeyEvent { code: Backspace, modifiers: NONE }
Ctrl+9: KeyEvent { code: Char('9'), modifiers: NONE }
Ctrl+0: KeyEvent { code: Char('0'), modifiers: NONE }
```
I don't know much about terminals. My first reaction was, that it is related to ascii control codes (https://en.wikipedia.org/wiki/Control_character).

This also happens in any terminal application I tested, like ranger or vim. Try pressing Ctrl+M (Return) or Ctrl+8 (Backspace) in vim.

I was confused why Ctrl+m doesn't work, but Ctrl+j or Ctrl+c does. It might be related to: https://github.com/crossterm-rs/crossterm/issues/371. 
If I understand it correctly, this was fixed by ignoring `/n` in raw_mode. 
https://github.com/crossterm-rs/crossterm/blob/9bc5cd3527a2d26caa6e2ccdc499beb4764fca95/src/event/sys/unix/parse.rs#L74

**Comment by sharnoff** [comment]
FWIW, I had originally fixed the Ctrl+J issue with #373. There's some information in the PR, as well as [this link](https://viewsourcecode.org/snaptoken/kilo/02.enteringRawMode.html#fix-ctrl-m), which you may find particularly relevant, @wags-1314.

The basic problem is this:

The way that characters are encoded in terminal emulators means that Ctrl+J and '\n' are _the same_ character -- it is not possible to distinguish them. AFAICT, the fix for #371 was just to reinterpret the byte sequence for '\n' as Ctrl+J, when we're in raw mode.

For Ctrl+J, this makes sense -- raw mode actually means that anything that _would_ be a newline (i.e. enter) gets reported as such, so anything with the byte sequence for Ctrl+J must _actually_ be Ctrl+J.

But for Ctrl+M, there isn't such a distinction. It is exactly the same as Enter -- that's why there aren't any terminal programs that are able to distinguish them.

So I don't know what crossterm should do. IMO, this behavior is the best it can be - (people more often want to check for Enter, not Ctrl+M, I think).

Also relevant: #569 - which IIRC would provide a way around this, for users of the [kitty](https://github.com/kovidgoyal/kitty) terminal.

**Comment by markus-bauer** [comment]
Related: https://github.com/crossterm-rs/crossterm/issues/594
The kitty protocol is based on this (https://www.leonerd.org.uk/hacks/fixterms/):
https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by stevenxxiu** [comment]
*WezTerm* also supports this.

**Comment by TimonPost** [comment]
Closing in favor of https://github.com/crossterm-rs/crossterm/issues/685.
