### ISSUE TITLE
Can't wait for events and get cursor position at the same time

### ISSUE THREAD

**Issue by Garmelon** [crossterm-rs/crossterm#672]
**Describe the bug**
On unix, when waiting for an event and then trying to get the cursor position (in another thread) at the same time, the latter function runs into a timeout and returns an error. This bug only occurs if no event is received during the timeout on the first thread.

**To Reproduce**
```rs
use std::time::Duration;
use std::{io, thread};

fn main() -> io::Result<()> {
    thread::spawn(crossterm::event::read);
    thread::sleep(Duration::from_millis(100));
    crossterm::cursor::position()?;
    Ok(())
}
```

1. `cargo new testproject` and add `crossterm = 0.23.2` to `Cargo.toml`
2. Replace `main.rs` with the code above
3. `cargo run` and wait two seconds. Don't press any key or resize the terminal during this period.
4. Observe the following error message: `Error: Custom { kind: Other, error: "The cursor position could not be read within a normal duration" }`

**Expected behavior**
The `crossterm::cursor::position()` call returns the cursor's position immediately.

**OS**
 - Linux (NixOS)

**Terminal/Console**
 - Gnome Console 42.beta
 - xterm

**Comment by sigmaSd** [comment]
I guess that's kind of expected since they both have to race reading from the terminal.

This behavior probably won't change because it would require keeping state.

A higher level wrapper library might be a better place to put such checks.

For a workakround for your specific case, you'll have to synchronize between the functions.(which probably mean you'll have to use poll instead of read)

**Comment by Garmelon** [comment]
I sort of expected that response. A warning in the documentation for `crossterm::cursor::position` could be useful, along the lines of
> Cannot be executed during blocking calls to `crossterm::event::read` on unix.

In my application, I was using an `EventStream` to obtain crossterm events, and I sometimes need the cursor position during rendering. This workaround means I'll probably have to poll for events manually every few microseconds or so, which doesn't seem too great. I can't just separate waiting for events and rendering into two alternating phases because there are also events from other sources that require a redraw. I also need to keep my poll duration low, otherwise successive cursor position calls will take too long since each position call will be followed by a poll timeout.

**Comment by sigmaSd** [comment]
These are just limitation of Unix terminals, personally I don't see much benifit in these warnings, It would be more interesting to add it if the above code works in windows, because I think giving a somewhat unified api is still a priority.

An other workaound you can use (which I use personally because using position is very slow) is to keep track of the cursor position manually, just use position once at the start of the app then keep track with math.

**Comment by TimonPost** [comment]
A comment would be nice to have here indeed.

**Comment by Garmelon** [comment]
> An other workaound you can use (which I use personally because using position is very slow) is to keep track of the cursor position manually, just use position once at the start of the app then keep track with math.

I'm measuring the actual displayed width of graphemes by writing them to the terminal and retrieving the cursor position afterwards, so I'll still need to use the actual position whenever I encounter new graphemes (see https://github.com/Garmelon/toss if you're interested).

I've wanted to try out my stuff on windows anyways, so I'll probably try it out there and open a PR with comments in a few days.

**Comment by sigmaSd** [comment]
Do you really need to do that, isn't that what unicode-width crate meant to achieve ?

**Comment by Garmelon** [comment]
Yes, but in practice, terminals behave slightly differently. For example, the emoji 🛡 has a width of 1 according to unicode-width but is displayed with a width of 2 in my terminal.

**Comment by Garmelon** [comment]
On windows, the above code sample seems to work without timing out.
