### ISSUE TITLE
Strategy to build TUI screensavers? Add terminal double buffering?

### ISSUE THREAD

**Issue by oiwn** [crossterm-rs/crossterm#733]
**Is your feature request related to a problem? Please describe.**

I'm building screensaver for terminal and stuck at problem, maybe i picked wrong approach? I draw on screen using terminal commands like MoveTo, PrintStylingContent. So all this happened in some kind of draw/flush/update loop. If i adding 

```stdout.queue(terminal::Clear(terminal::ClearType::All))?``` 

before drawing another one frame, the screen starting to blink, like it's very heavy operation. I end up calculating diffs between frames and Print(' '.black()) instead of cleaning whole screen. 

**Describe the solution you'd like**

Able to "project" buffer with text into the terminal. But as far as i understand working with terminal it's not like drawing on screen, you can't just project ```Vec<u8>``` (or can?) into the terminal since some commands to draw even single character are more complex (need to transfer additional data about style).

**Comment by markus-bauer** [comment]
I'm not sure, but I think the flickering happens because you literally tell the terminal to first clear all, and then print. Depending on the terminal emulator, it will buffer this internally, or apply both instructions, which causes flicker.

You already found the solution: Instead of clearing, print over the cells that changed, instead of clearing the screen.

If you need to optimize it, then you will have to keep track of the current state, and only print what changed.
Tui, for example, has an offscreen buffer and additional checks to minimize terminal instructions:
- buffer: a vec of cells
https://github.com/fdehau/tui-rs/blob/master/src/buffer.rs
- only draw the cells that changed:
https://github.com/fdehau/tui-rs/blob/fafad6c96109610825aad89c4bba5253e01101ed/src/buffer.rs#L431
- drawing with crossterm: This also minimizes the instructions, by tracking, what the current postion and attributes are. So that it only sends instructions when needed.
https://github.com/fdehau/tui-rs/blob/master/src/backend/crossterm.rs

If you just want something that works, use a high level library, like tui.

**Comment by oiwn** [comment]
Thank you for detailed answer!

**Comment by TimonPost** [comment]
This is a higher-level concern for terminal application builders. Looking at libraries such as cursive, broot, r3bel, tui might give more insight in how they work around this problem. 

 https://crates.io/crates/r3bl_rs_utils_core

**Comment by oiwn** [comment]
@markus-bauer https://github.com/oiwn/tui-screen-savers-rs i did with diffs buffer with decent performance.
