### ISSUE TITLE
expose Attributes inner value

### ISSUE THREAD

**Issue by bogzbonny** [crossterm-rs/crossterm#774]
**Is your feature request related to a problem? Please describe.**
For my application I'm storing CUI related information encoded using bincode, namely text Attributes are being stored. Currently the only way I've been able to store the relevant information is by checking each `Attribute` via the `Attributes.has(..)` function, then setting them in a different struct which I then encode with bincode. 

**Describe alternatives you've considered if any**
The current alternative that which I've implemented described in the first paragraph.. it's a bit cumbersome. 

**Describe the solution you'd like**
It would be really nice to have the the inner value of attributes exposed. I see two basic options: 
1) make the value pub directly (`pub struct Attributes(u32);` -> `pub struct Attributes(pub u32);`) 
2) have `Attributes` implement a function to expose the value, maybe something such as  `pub const fn inner_value(&self) -> u32`. Additionally I could see a function like this being made only available under a `internals` feature flag if desired... however I'm noticing that crossterm does not yet have such a flag. 

Let me know your thoughts! THANK YOU for all the incredible work that's gone into this library :)

**Comment by joshka** [comment]
I'm looking at that code for the first time, and replying as someone who's been helping out on PRs recent, not one that has significant amounts of context on this. (I say this to make it clear I'm not talking on behalf of the project, just as an interested party).

The inner value seems more like an implementation detail more than something that should be publicly exposed on an API. In particular, the number of items in the [SGR table](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR) is more than 32, so this approach to storing the attributes has a problem if all the items are implemented 1 bit for 1 attribute. Obviously colors have been carved out, but I think some of the attributes are just plain missing.

If I was re-designing Attribute(s) right now, I'd consider using bitflags instead of manually designing that, or if instead of bitlfage attributes enum was kept around, using Strum to define the extra data instead of a custom macro. As a slight performance improvment, Also I'd want to see the SGR display print all the attributes at once instead of one by one (to save a few characters. (`Esc[1;2;79;m` instead of `Esc[1m;Esc[2m;Esc[79m`). This would be a small performance improvement in attribute heavy apps, similar to the improvement in the colors rendering I did recently.

From an implementation perspective, Did you consider looking at an approach that makes that internal value not relevant. Perhaps implement `IntoIterator<Item = Attribute>` on Attributes instead (or some similar idea)? This would give you a more stable implementation (at the cost of having an iteration instead of a single value).

**Comment by bogzbonny** [comment]
My system requires that I have an Attributes type of my own which must be encoded with bincode. My current approach is to just make my own Attributes struct for encoding/decoding then translate it into the crossterm Attributes struct, not the prettiest but it works.. so in this way the internal value is made irrelevant, however it's just a few extra steps. I figured it would be good to reuse the same type of Attributes for my application, however I cannot while the inner value stays private. 

Interesting wrt attribute printing, I wasn't aware that the attributes were relayed to the terminal one by one. yes that seems like an opportunity for optimization. 

Well maybe what really needs to happen is some form of attributes refactor based on what I'm hearing here haha. btw I only counted about 28 attributes in crossterm - I imagine that many of the missing attributes (besides colours which are a separate system in crossterm) are of the "rarely" supported category, or have other simple ways of achieving the same result with crossterm. Going through through all the of the attributes in crossterm within kitty console, I found only about half of them to be supported anyways. So maybe filling in all those SGR codes would not actually provide any additional utility and 32 codes is plenty.  Maybe it's those ANSI esc sequences that need a refactor!

**Comment by joshka** [comment]
Just for reference, here's SGR across iTerm2, Kitty, Alacritty, and WezTerm:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/e5c3d30b-8af9-40af-82a7-7084e7a818d2">

I wrote some characterization unit tests for `Attribute` and noticed that there's an off by one bug in `Attribute::bytes()`. `Reset` => `0x2` where `0x1` seems like it would make more sense in context, and every subsequent variant is 2x the necessary value. That likely should be fixed (and would break your bincode serialization if it relied on that value and it then changed). This also also leaves only 3 values when there should be 4 available. Wezterm supports superscript and subscript, which would take up those 3 more (including the no-super/subscript variant).

There's also an edge case where a ANSI supports turning off an attribute and then turning it on in the one command, but crossterm always does on then off for the specific attributes, and the reset is always first (never last). I suspect the right way to model this in crossterm is as a full SGR command that accepts an ordered list of attributes (including colors) instead of as a custom bitfield. But this is an area that I wouldn't want to break any existing code.

The problem with making that inner value public is that any future change to this value seems like it would break your serialization. I'd guess that the most future proof serialization approach is to do pretty much what you're already doing (extract each attribute).

**Comment by bogzbonny** [comment]
Very interesting, thank you for that graphic. Is the lower-right wezterm? seems to be the only terminal supporting overlined (also sub and superscript too). Personally I wouldn't worry about breaking changes, just make a breaking release with a migration guide, I deal with breaking changes all the time in the libraries I use. HOWEVER I understand the hesitancy with regards to making a breaking change inside Attributes, if for instance, the type remained the same but the meaning that the value of that u32 represented completely changed, it would break programs but the compiler wouldn't let you know. 

I'd recommend opening another issue for the bug you've discovered. After I can close this issue, I'm not attached to having the inner workings as pub

**Comment by joshka** [comment]
yep - wezterm also supports both blinking rates - the others don't seem to (I'm sure there's probably settings, but I've mostly only setup iTerm2.
