### ISSUE TITLE
[macos] `ctrl-i` is interpreted as tab

### ISSUE THREAD

**Issue by FrancescElies** [crossterm-rs/crossterm#911]
**Describe the bug**
`ctrl-i` seems to be interpreted as tab

**To Reproduce**
1. run `cargo run --example event-read`
2. Click on `i`, then `ctrl-i`, then `esc` to quit
4. See output `ctrl-i` is interpreted as tab

https://github.com/user-attachments/assets/888d3178-2347-475d-97a2-2348542db207

**OS**
 - MacOS 14.5

**Terminal/Console**
 - wezterm, but same happens on iterm or the default terminal from mac

**Comment by joshka** [comment]
You might find it a fun rabbit hole to go down as to why this is.  But it's by design and likely not crossterm handling this, but your terminal. There are various control combinations that are equivalent, e.g. ctrl+[ Esc, ctrl+m Enter,and ctrl+i Tab. There are ways of disambiguating these, but they require terminal support and the app to turn on the ability.

See https://sw.kovidgoyal.net/kitty/keyboard-protocol/#legacy-text-keys for some in depth info. And the set keyboard enhancement flags command for turning this on (not supported everywhere, be careful)

**Comment by FrancescElies** [comment]
I see 😅, I was not aware of that, I guess I will keep have to keep that in in mind when binding shortcuts and keep myself away from `ctrl-i`, `ctrl-m`, 

closing.

**Comment by joshka** [comment]
Confirmed that crossterm isn't doing anything special here - just mapping `\t` => `KeyCode::Tab`.
https://github.com/search?q=repo%3Acrossterm-rs%2Fcrossterm+%22keycode%3A%3Atab%22&type=code
